### ISSUE TITLE
when we use scrolling at tap  in same page and scroll down and click to next tap and back again click to first tap then it  doesn't scroll at top 

### ISSUE THREAD

**Issue by Prabin1111** [orizens/ngx-infinite-scroll#327]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

### Steps To Reproduce / Demo (if applicable)
[ ] Please share a [stackblitz](https://stackblitz.com/) or [plunkr](https://plnkr.co/) demo reproducing this issue  

### Your Environment

- [ ] Version used: 
- [ ] Browser Name and version:
- [ ] (Optional) Operating System and version (desktop or mobile):
- [ ] (Optional) Link to your project:

**Comment by oilujc** [comment]
Any solution? Same problem

**Comment by LeoLfL** [comment]
Agree. it would be nice to have some reset method for the scroll. currently, I fixed it using this solution:

in .ts file
  `@ViewChild(InfiniteScrollDirective) infiniteScrollDirective;`

and when u need to reset scroll logic : 

```
    this.infiniteScrollDirective.disposeScroller.unsubscribe();
    this.infiniteScrollDirective.setup();
```

**Comment by Kiranrajkathula** [comment]
@SiarheiBokuts this works absolutely fine. Thanks

**Comment by sismananitas** [comment]
Maybe try, when changing tap
this.infiniteScrollDirective.destroyScroller();
this.infiniteScrollDirective.setup();

**Comment by shyamal890** [comment]
@orizens this issue is still there, is there a permanent solution to this issue?
